name: Publish_develop_branch_NuGetPackage

on:
  push:
    branches:
      - develop  # Triggers the workflow on pushes to the 'develop' branch

jobs:
  build-job:
    uses: CoreBrew/github-actions-workflows/.github/workflows/Publish_Develop_Branch.yml@main # call external workflow
    
    

