name: ManTrig_Deploy_Release_NuGet_Packages

on:
  workflow_dispatch: 

jobs:
  ManTrig:
    # call shared external workflow        
    uses: CoreBrew/github-actions-workflows/.github/workflows/dotNet_ReleaseNuGetPackage_Workflow.yml@main
    with:
      buildConfiguration: "Release"
      releaseStage: "" #empty release stage, should also be the default
    secrets:
      NuGetApiKey: ${{ secrets.UPDATE_ALL_PACKAGES_KEY }}      